services:
  - type: web
    name: task-optimizer-ai-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: BACKEND_CORS_ORIGINS
        fromService:
          type: web
          name: task-optimizer-ai-frontend
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: task-optimizer-ai-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: task-optimizer-ai-backend
          envVarKey: RENDER_EXTERNAL_URL
